server:
  port: 8081
  
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.56.101:3306/db_member?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      #初始化时建立物理连接的个数
      initial-size: 5      
      #获取连接时最大等待时间，单位毫秒
      max-wait: 60000      
      #最大连接池数量 maxIdle已经不再使用
      max-active: 20      
      #是否缓存preparedStatement,mysql5.5+建议开启
      pool-prepared-statements: true     
      #当值大于0时poolPreparedStatements会自动修改为true
      max-pool-prepared-statement-per-connection-size: 20      
      #既作为检测的间隔时间又作为testWhileIdel执行的依据
      time-between-eviction-runs-millis: 60000    
      #销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
      min-evictable-idle-time-millis: 300000      
      #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true     
      #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-borrow: false     
      #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false     
      async-init: true  
      #用来检测连接是否有效的sql 必须是一个查询语句
      validation-query: SELECT 'x' 
      #当数据库抛出不可恢复的异常时,抛弃该连接
      #exception-sorter: true 
      #合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
      ##开启日志输出
      filter:
        slf4j:
          result-set-log-error-enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
        stat:
          log-slow-sql: true
          merge-sql: true
          slow-sql-millis: 500
##mybatis配置     
mybatis-plus:
  check-config-location: true
  mapper-locations:
  - classpath:mybtais/mapper/*.xml
  type-aliases-package: com.example.sharding.entity
  
##sharding 配置

  
# Logger Config
logging:
  level:
    root: info
    com.baomidou.mybatisplus.samples: debug
    com.alibaba.druid.sql: debug